# Generated by Django 6.0.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_lease_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the maintenance request', null=True, upload_to='maintenance_images/%Y/%m/'),
        ),
    ]
