# Generated by Django 6.0.2 on 2026-03-03 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_maintenance_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Explicit due date for this rent payment', null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Security deposit amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
