# Generated by Django 6.0.2 on 2026-03-03 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_payment_options_payment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, help_text='Auto-generated receipt file', null=True, upload_to='receipts/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Lease start date')),
                ('end_date', models.DateField(help_text='Lease end date')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lease_document', models.FileField(blank=True, null=True, upload_to='leases/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.tenantprofile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.unit')),
            ],
            options={
                'db_table': 'tenant_leases',
                'ordering': ['-start_date'],
            },
        ),
    ]
