# Generated by Django 6.0.3 on 2026-03-10 11:26

import properties.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_maintenancerequest_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the maintenance request (JPEG/PNG/WebP, max 5MB)', null=True, upload_to='maintenance_images/%Y/%m/', validators=[properties.validators.validate_upload]),
        ),
        migrations.AlterField(
            model_name='paymentevidence',
            name='file',
            field=models.FileField(help_text='Payment screenshot or document (JPEG/PNG/WebP/PDF, max 5MB)', upload_to='payment_evidence/%Y/%m/', validators=[properties.validators.validate_upload]),
        ),
    ]
