# Generated by Django 6.0.3 on 2026-03-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_maintenancerequest_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_category',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Security Deposit', 'Security Deposit')], default='Rent', max_length=50),
        ),
    ]
