# Generated by Django 6.0.3 on 2026-03-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_payment_payment_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
